//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursPekin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public Nullable<int> NumberContract { get; set; }
        public Nullable<int> ContractTypeId { get; set; }
        public decimal Summa { get; set; }
        public string Avatar { get; set; }
        public Nullable<System.DateTime> ContactTime { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string prosess { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual Userman Userman { get; set; }
    }
}
